#############################################################################
# Makefile for building: QmlLearningPro
# Generated by qmake (3.1) (Qt 5.12.6)
# Project:  QmlLearningPro.pro
# Template: subdirs
# Command: C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\bin\qmake.exe -o Makefile QmlLearningPro.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-CanvasSector \
		sub-CrazyMath \
		sub-MapFermatSpiral \
		sub-MapGetdistance \
		sub-MenuForButton \
		sub-MenuForListview \
		sub-MenuForRepeater \
		sub-MenuForTabBar \
		sub-NetTools \
		sub-ParaProgressBar \
		sub-Popup \
		sub-TranslationsDemo \
		sub-VirtualJoystick


sub-CanvasSector-qmake_all:  FORCE
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	cd CanvasSector\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && $(MAKE) -f Makefile qmake_all
sub-CanvasSector: $(MAKEFILE) FORCE
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-CanvasSector-make_first: FORCE
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-CanvasSector-all: FORCE
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-CanvasSector-clean: FORCE
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-CanvasSector-distclean: FORCE
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-CanvasSector-install_subtargets: FORCE
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-CanvasSector-uninstall_subtargets: FORCE
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-CrazyMath-qmake_all:  FORCE
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	cd CrazyMath\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && $(MAKE) -f Makefile qmake_all
sub-CrazyMath: $(MAKEFILE) FORCE
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-CrazyMath-make_first: FORCE
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-CrazyMath-all: FORCE
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-CrazyMath-clean: FORCE
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-CrazyMath-distclean: FORCE
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-CrazyMath-install_subtargets: FORCE
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-CrazyMath-uninstall_subtargets: FORCE
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MapFermatSpiral-qmake_all:  FORCE
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	cd MapFermatSpiral\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && $(MAKE) -f Makefile qmake_all
sub-MapFermatSpiral: $(MAKEFILE) FORCE
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MapFermatSpiral-make_first: FORCE
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MapFermatSpiral-all: FORCE
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MapFermatSpiral-clean: FORCE
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MapFermatSpiral-distclean: FORCE
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MapFermatSpiral-install_subtargets: FORCE
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MapFermatSpiral-uninstall_subtargets: FORCE
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MapGetdistance-qmake_all:  FORCE
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	cd MapGetdistance\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && $(MAKE) -f Makefile qmake_all
sub-MapGetdistance: $(MAKEFILE) FORCE
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MapGetdistance-make_first: FORCE
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MapGetdistance-all: FORCE
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MapGetdistance-clean: FORCE
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MapGetdistance-distclean: FORCE
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MapGetdistance-install_subtargets: FORCE
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MapGetdistance-uninstall_subtargets: FORCE
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MenuForButton-qmake_all:  FORCE
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	cd MenuForButton\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && $(MAKE) -f Makefile qmake_all
sub-MenuForButton: $(MAKEFILE) FORCE
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MenuForButton-make_first: FORCE
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MenuForButton-all: FORCE
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MenuForButton-clean: FORCE
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MenuForButton-distclean: FORCE
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MenuForButton-install_subtargets: FORCE
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MenuForButton-uninstall_subtargets: FORCE
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MenuForListview-qmake_all:  FORCE
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	cd MenuForListview\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && $(MAKE) -f Makefile qmake_all
sub-MenuForListview: $(MAKEFILE) FORCE
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MenuForListview-make_first: FORCE
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MenuForListview-all: FORCE
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MenuForListview-clean: FORCE
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MenuForListview-distclean: FORCE
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MenuForListview-install_subtargets: FORCE
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MenuForListview-uninstall_subtargets: FORCE
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MenuForRepeater-qmake_all:  FORCE
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	cd MenuForRepeater\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && $(MAKE) -f Makefile qmake_all
sub-MenuForRepeater: $(MAKEFILE) FORCE
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MenuForRepeater-make_first: FORCE
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MenuForRepeater-all: FORCE
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MenuForRepeater-clean: FORCE
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MenuForRepeater-distclean: FORCE
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MenuForRepeater-install_subtargets: FORCE
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MenuForRepeater-uninstall_subtargets: FORCE
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MenuForTabBar-qmake_all:  FORCE
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	cd MenuForTabBar\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && $(MAKE) -f Makefile qmake_all
sub-MenuForTabBar: $(MAKEFILE) FORCE
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MenuForTabBar-make_first: FORCE
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MenuForTabBar-all: FORCE
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MenuForTabBar-clean: FORCE
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MenuForTabBar-distclean: FORCE
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MenuForTabBar-install_subtargets: FORCE
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MenuForTabBar-uninstall_subtargets: FORCE
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-NetTools-qmake_all:  FORCE
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	cd NetTools\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && $(MAKE) -f Makefile qmake_all
sub-NetTools: $(MAKEFILE) FORCE
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-NetTools-make_first: FORCE
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-NetTools-all: FORCE
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-NetTools-clean: FORCE
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-NetTools-distclean: FORCE
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-NetTools-install_subtargets: FORCE
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-NetTools-uninstall_subtargets: FORCE
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-ParaProgressBar-qmake_all:  FORCE
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	cd ParaProgressBar\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && $(MAKE) -f Makefile qmake_all
sub-ParaProgressBar: $(MAKEFILE) FORCE
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-ParaProgressBar-make_first: FORCE
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-ParaProgressBar-all: FORCE
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-ParaProgressBar-clean: FORCE
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-ParaProgressBar-distclean: FORCE
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-ParaProgressBar-install_subtargets: FORCE
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-ParaProgressBar-uninstall_subtargets: FORCE
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Popup-qmake_all:  FORCE
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	cd Popup\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && $(MAKE) -f Makefile qmake_all
sub-Popup: $(MAKEFILE) FORCE
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Popup-make_first: FORCE
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Popup-all: FORCE
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Popup-clean: FORCE
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Popup-distclean: FORCE
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Popup-install_subtargets: FORCE
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Popup-uninstall_subtargets: FORCE
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-TranslationsDemo-qmake_all:  FORCE
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	cd TranslationsDemo\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && $(MAKE) -f Makefile qmake_all
sub-TranslationsDemo: $(MAKEFILE) FORCE
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-TranslationsDemo-make_first: FORCE
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-TranslationsDemo-all: FORCE
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-TranslationsDemo-clean: FORCE
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-TranslationsDemo-distclean: FORCE
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-TranslationsDemo-install_subtargets: FORCE
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-TranslationsDemo-uninstall_subtargets: FORCE
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-VirtualJoystick-qmake_all:  FORCE
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	cd VirtualJoystick\ && $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && $(MAKE) -f Makefile qmake_all
sub-VirtualJoystick: $(MAKEFILE) FORCE
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-VirtualJoystick-make_first: FORCE
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-VirtualJoystick-all: FORCE
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-VirtualJoystick-clean: FORCE
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-VirtualJoystick-distclean: FORCE
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-VirtualJoystick-install_subtargets: FORCE
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-VirtualJoystick-uninstall_subtargets: FORCE
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: QmlLearningPro.pro C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\win32-msvc\qmake.conf C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\spec_pre.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\common\angle.conf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\common\windows-vulkan.conf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\common\msvc-desktop.conf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\qconfig.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\qt_functions.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\qt_config.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\win32-msvc\qmake.conf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\common\msvc-version.conf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\toolchain.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\default_pre.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\win32\default_pre.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\resolve_config.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\default_post.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\qml_debug.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\precompile_header.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\warn_on.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\qmake_use.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\file_copies.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\win32\windows.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\exceptions.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\yacc.prf \
		C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\lex.prf \
		QmlLearningPro.pro
	$(QMAKE) -o Makefile QmlLearningPro.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\spec_pre.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\common\angle.conf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\common\windows-vulkan.conf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\common\msvc-desktop.conf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\qconfig.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\qt_functions.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\qt_config.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\win32-msvc\qmake.conf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\spec_post.prf:
.qmake.stash:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\common\msvc-version.conf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\toolchain.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\default_pre.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\win32\default_pre.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\resolve_config.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\default_post.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\qml_debug.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\precompile_header.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\warn_on.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\qmake_use.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\file_copies.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\win32\windows.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\testcase_targets.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\exceptions.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\yacc.prf:
C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\lex.prf:
QmlLearningPro.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile QmlLearningPro.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-CanvasSector-qmake_all sub-CrazyMath-qmake_all sub-MapFermatSpiral-qmake_all sub-MapGetdistance-qmake_all sub-MenuForButton-qmake_all sub-MenuForListview-qmake_all sub-MenuForRepeater-qmake_all sub-MenuForTabBar-qmake_all sub-NetTools-qmake_all sub-ParaProgressBar-qmake_all sub-Popup-qmake_all sub-TranslationsDemo-qmake_all sub-VirtualJoystick-qmake_all FORCE

make_first: sub-CanvasSector-make_first sub-CrazyMath-make_first sub-MapFermatSpiral-make_first sub-MapGetdistance-make_first sub-MenuForButton-make_first sub-MenuForListview-make_first sub-MenuForRepeater-make_first sub-MenuForTabBar-make_first sub-NetTools-make_first sub-ParaProgressBar-make_first sub-Popup-make_first sub-TranslationsDemo-make_first sub-VirtualJoystick-make_first  FORCE
all: sub-CanvasSector-all sub-CrazyMath-all sub-MapFermatSpiral-all sub-MapGetdistance-all sub-MenuForButton-all sub-MenuForListview-all sub-MenuForRepeater-all sub-MenuForTabBar-all sub-NetTools-all sub-ParaProgressBar-all sub-Popup-all sub-TranslationsDemo-all sub-VirtualJoystick-all  FORCE
clean: sub-CanvasSector-clean sub-CrazyMath-clean sub-MapFermatSpiral-clean sub-MapGetdistance-clean sub-MenuForButton-clean sub-MenuForListview-clean sub-MenuForRepeater-clean sub-MenuForTabBar-clean sub-NetTools-clean sub-ParaProgressBar-clean sub-Popup-clean sub-TranslationsDemo-clean sub-VirtualJoystick-clean  FORCE
distclean: sub-CanvasSector-distclean sub-CrazyMath-distclean sub-MapFermatSpiral-distclean sub-MapGetdistance-distclean sub-MenuForButton-distclean sub-MenuForListview-distclean sub-MenuForRepeater-distclean sub-MenuForTabBar-distclean sub-NetTools-distclean sub-ParaProgressBar-distclean sub-Popup-distclean sub-TranslationsDemo-distclean sub-VirtualJoystick-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-CanvasSector-install_subtargets sub-CrazyMath-install_subtargets sub-MapFermatSpiral-install_subtargets sub-MapGetdistance-install_subtargets sub-MenuForButton-install_subtargets sub-MenuForListview-install_subtargets sub-MenuForRepeater-install_subtargets sub-MenuForTabBar-install_subtargets sub-NetTools-install_subtargets sub-ParaProgressBar-install_subtargets sub-Popup-install_subtargets sub-TranslationsDemo-install_subtargets sub-VirtualJoystick-install_subtargets FORCE
uninstall_subtargets: sub-CanvasSector-uninstall_subtargets sub-CrazyMath-uninstall_subtargets sub-MapFermatSpiral-uninstall_subtargets sub-MapGetdistance-uninstall_subtargets sub-MenuForButton-uninstall_subtargets sub-MenuForListview-uninstall_subtargets sub-MenuForRepeater-uninstall_subtargets sub-MenuForTabBar-uninstall_subtargets sub-NetTools-uninstall_subtargets sub-ParaProgressBar-uninstall_subtargets sub-Popup-uninstall_subtargets sub-TranslationsDemo-uninstall_subtargets sub-VirtualJoystick-uninstall_subtargets FORCE

sub-CanvasSector-debug:
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-CrazyMath-debug:
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MapFermatSpiral-debug:
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MapGetdistance-debug:
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MenuForButton-debug:
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MenuForListview-debug:
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MenuForRepeater-debug:
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MenuForTabBar-debug:
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-NetTools-debug:
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-ParaProgressBar-debug:
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Popup-debug:
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-TranslationsDemo-debug:
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-VirtualJoystick-debug:
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-CanvasSector-debug sub-CrazyMath-debug sub-MapFermatSpiral-debug sub-MapGetdistance-debug sub-MenuForButton-debug sub-MenuForListview-debug sub-MenuForRepeater-debug sub-MenuForTabBar-debug sub-NetTools-debug sub-ParaProgressBar-debug sub-Popup-debug sub-TranslationsDemo-debug sub-VirtualJoystick-debug

sub-CanvasSector-release:
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-CrazyMath-release:
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MapFermatSpiral-release:
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MapGetdistance-release:
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MenuForButton-release:
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MenuForListview-release:
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MenuForRepeater-release:
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MenuForTabBar-release:
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-NetTools-release:
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-ParaProgressBar-release:
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Popup-release:
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-TranslationsDemo-release:
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-VirtualJoystick-release:
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-CanvasSector-release sub-CrazyMath-release sub-MapFermatSpiral-release sub-MapGetdistance-release sub-MenuForButton-release sub-MenuForListview-release sub-MenuForRepeater-release sub-MenuForTabBar-release sub-NetTools-release sub-ParaProgressBar-release sub-Popup-release sub-TranslationsDemo-release sub-VirtualJoystick-release

sub-CanvasSector-check:
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-CrazyMath-check:
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MapFermatSpiral-check:
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MapGetdistance-check:
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MenuForButton-check:
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MenuForListview-check:
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MenuForRepeater-check:
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MenuForTabBar-check:
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-NetTools-check:
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-ParaProgressBar-check:
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Popup-check:
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-TranslationsDemo-check:
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-VirtualJoystick-check:
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-CanvasSector-check sub-CrazyMath-check sub-MapFermatSpiral-check sub-MapGetdistance-check sub-MenuForButton-check sub-MenuForListview-check sub-MenuForRepeater-check sub-MenuForTabBar-check sub-NetTools-check sub-ParaProgressBar-check sub-Popup-check sub-TranslationsDemo-check sub-VirtualJoystick-check

sub-CanvasSector-benchmark:
	@if not exist CanvasSector\ mkdir CanvasSector\ & if not exist CanvasSector\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CanvasSector\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CanvasSector\CanvasSector.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-CrazyMath-benchmark:
	@if not exist CrazyMath\ mkdir CrazyMath\ & if not exist CrazyMath\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CrazyMath\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\CrazyMath\CrazyMath.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MapFermatSpiral-benchmark:
	@if not exist MapFermatSpiral\ mkdir MapFermatSpiral\ & if not exist MapFermatSpiral\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapFermatSpiral\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapFermatSpiral\MapFermatSpiral.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MapGetdistance-benchmark:
	@if not exist MapGetdistance\ mkdir MapGetdistance\ & if not exist MapGetdistance\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MapGetdistance\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MapGetdistance\MapGetdistance.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MenuForButton-benchmark:
	@if not exist MenuForButton\ mkdir MenuForButton\ & if not exist MenuForButton\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForButton\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForButton\MenuForButton.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MenuForListview-benchmark:
	@if not exist MenuForListview\ mkdir MenuForListview\ & if not exist MenuForListview\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForListview\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForListview\MenuForListview.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MenuForRepeater-benchmark:
	@if not exist MenuForRepeater\ mkdir MenuForRepeater\ & if not exist MenuForRepeater\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForRepeater\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForRepeater\MenuForRepeater.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MenuForTabBar-benchmark:
	@if not exist MenuForTabBar\ mkdir MenuForTabBar\ & if not exist MenuForTabBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MenuForTabBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\MenuForTabBar\MenuForTabBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-NetTools-benchmark:
	@if not exist NetTools\ mkdir NetTools\ & if not exist NetTools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetTools\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\NetTools\NetTools.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-ParaProgressBar-benchmark:
	@if not exist ParaProgressBar\ mkdir ParaProgressBar\ & if not exist ParaProgressBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ParaProgressBar\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\ParaProgressBar\ParaProgressBar.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Popup-benchmark:
	@if not exist Popup\ mkdir Popup\ & if not exist Popup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Popup\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\Popup\Popup.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-TranslationsDemo-benchmark:
	@if not exist TranslationsDemo\ mkdir TranslationsDemo\ & if not exist TranslationsDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TranslationsDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\TranslationsDemo\TranslationsDemo.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-VirtualJoystick-benchmark:
	@if not exist VirtualJoystick\ mkdir VirtualJoystick\ & if not exist VirtualJoystick\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VirtualJoystick\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\22_Qt\1_MyProject\QmlLearningPro\QmlLearningPro\VirtualJoystick\VirtualJoystick.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-CanvasSector-benchmark sub-CrazyMath-benchmark sub-MapFermatSpiral-benchmark sub-MapGetdistance-benchmark sub-MenuForButton-benchmark sub-MenuForListview-benchmark sub-MenuForRepeater-benchmark sub-MenuForTabBar-benchmark sub-NetTools-benchmark sub-ParaProgressBar-benchmark sub-Popup-benchmark sub-TranslationsDemo-benchmark sub-VirtualJoystick-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

